---
- name: Install and Configure MySQL
  hosts: localhost

  become: true

  tasks:
    - name: Install MySQL Server
      apt:
        name: "{{ mysql_package }}"
        state: present
    - name: Start MySQL Service
      service:
        name: "{{ mysql_service }}"
        state: started
        enabled: yes
