---
- name: Deploy Web and Database Servers
  hosts: localhost
  connection: local

  tasks:
    - name: Apply webserver role
      include_role:
        name: webserver
      tags: webserver

    - name: Apply dbserver role
      include_role:
        name: dbserver
      tags: dbserver
